### ISSUE TITLE
Sun/Moon - Missing Pinap Berry

### ISSUE THREAD

**Issue by Arminius** [PhilMurwin/PokemonChecklists#33]
There is also the Pinap berry in Sun and moon, which is missing from the list.

**Comment by PhilMurwin** [comment]
This has been added.  It could still use a tooltip for the where/how to get it but I can't find the Pinap berry listed anywhere for Pokemon Sun/Moon.

**Comment by Arminius** [comment]
It's on [Serebii](http://www.serebii.net/itemdex/pinapberry.shtml). Says it's found in Royal Avenue, but I don't know where exactly. Probably from the guy in the Megamart.

**Comment by PhilMurwin** [comment]
Thanks for the tip! I've added a tooltip reflecting this information.
