### ISSUE TITLE
Minior Core Colors Name Incorrect

### ISSUE THREAD

**Issue by pegurnee** [PhilMurwin/PokemonChecklists#36]
The Minior color options are red, orange, yellow, green, blue, indigo, and violet, not red, orange, yellow, green, blue, indigo, and purple.

Purple under Minior colors should be changed to violet.

Also, should the shiny black color actually be listed as something needed to get?

**Comment by PhilMurwin** [comment]
Thanks for the feedback!

1. I've seen either purple or violet listed depending on where you look; I'm going to leave it as is.
2. If someone is going to go to the trouble of tracking catching the various colors of Minior they may also wish to check that they've caught the shiny version as well.  I'll leave that up to the individual to be concerned about checking that box or not.
