### ISSUE TITLE
Bug: Tooltips get cut off if they extend upwards to another section

### ISSUE THREAD

**Issue by brandtmaynard** [PhilMurwin/PokemonChecklists#37]
Occurs on Windows 10 using Google Chrome Version 61.0.3163.100.

If a subtask at the top of its section has a long enough tooltip, it gets cut off by the section above it. This does not happen with the tooltip for the Mega-Evolution Stones task, indicating that the problem is specifically with subtasks. See attached image:
![usum checklist tooltip bug](https://user-images.githubusercontent.com/11731183/33236535-a6c48ed0-d224-11e7-9b59-da0c6532cffc.png)

**Comment by PhilMurwin** [comment]
Thanks for the feedback, this has been fixed.
