### ISSUE TITLE
Show Alolan Persian to Oak

### ISSUE THREAD

**Issue by Araraura** [PhilMurwin/PokemonChecklists#40]
I'm trying to do that, but he just tells me to show him that, even though I already have one in my dex.

**Comment by PhilMurwin** [comment]
I believe this is a repeat item in my list.  It shows up under the Pokedex side quests as well as the sub events.  You should get a Love Ball for your troubles.

The tasks that are for the same thing are:
* Show Alolan Persian to Samson Oak at the Malie City Library
* Get a rare Poke Ball from Samson Oak at the library

I wish I could be more helpful but I haven't gotten very far in the game myself so I'm at the mercy of the information I've found on the topic...
