### ISSUE TITLE
USUM: "Actress Meredith" sub-events description truncated and missing follow-ups

### ISSUE THREAD

**Issue by markikollasch** [PhilMurwin/PokemonChecklists#43]
USUM contains several events for encountering Actress Meredith, but only the first one is listed in the Sub-Events task list, the one at Melemele Meadow. Additionally, the tooltip reads `"Find Meredith in Melemele Meadow, "`, which ends in the middle of a sentence.

**Comment by PhilMurwin** [comment]
Thanks for the heads up, I've fixed this oversight! 👍
