### ISSUE TITLE
[Feature Request] Living Dex (by generation)

### ISSUE THREAD

**Issue by Ninjistix** [PhilMurwin/PokemonChecklists#56]
edit: didn't mean to submit empty description, but would it be possible to add a living dex tracker (by generation?) 

i originally found this searching for a dex list, that i could either print and chick off what i caught per what game, to help me build a living dex for each game.

edit2: i can also help write/finish the living dex for other generations, if a sample for one generation is made.

**Comment by PhilMurwin** [comment]
I'd highly recommend checking out https://pokedextracker.com/ I use that one myself; it's fantastic.

**Comment by Ninjistix** [comment]
yeah but that's specifically for gen 6+, I want to create a living dex by generation or game, from gen1-7
